### ISSUE TITLE
Permanent disconnects

### ISSUE THREAD

**Issue by npo6ka** [bartimaeusnek/bartworks#33]
I play on the GTNH modpack and faced such a problem. When I travel around the planet rose 128b and in some chunks I am constantly thrown out from the server. In this case, the server does not give any errors.

Client log:
[20:40:53] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel BartWorks
java.lang.StackOverflowError
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:845) ~[apx.class:?]
	at net.minecraft.world.World.func_147438_o(World.java:2540) ~[ahb.class:?]
	at com.github.bartimaeusnek.bartworks.system.material.BW_MetaGenerated_Ores.onNeighborChange(BW_MetaGenerated_Ores.java:173) ~[BW_MetaGenerated_Ores.class:?]
	at net.minecraft.world.World.func_147453_f(World.java:3875) ~[ahb.class:?]
	at net.minecraft.world.World.func_147455_a(World.java:2603) ~[ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851) ~[apx.class:?]
	at net.minecraft.world.World.func_147438_o(World.java:2540) ~[ahb.class:?]
	at com.github.bartimaeusnek.bartworks.system.material.BW_MetaGenerated_Ores.onNeighborChange(BW_MetaGenerated_Ores.java:173) ~[BW_MetaGenerated_Ores.class:?]
	at net.minecraft.world.World.func_147453_f(World.java:3875) ~[ahb.class:?]
	at net.minecraft.world.World.func_147455_a(World.java:2603) ~[ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851) ~[apx.class:?]
	at net.minecraft.world.World.func_147438_o(World.java:2540) ~[ahb.class:?]
	at com.github.bartimaeusnek.bartworks.system.material.BW_MetaGenerated_Ores.onNeighborChange(BW_MetaGenerated_Ores.java:173) ~[BW_MetaGenerated_Ores.class:?]

**Comment by bartimaeusnek** [comment]
it is known, thread is here:
https://github.com/GTNewHorizons/NewHorizons/issues/4777
